name: pipeline.yaml
on: 
    push:
        branches: 
         - v[0-9].[0-9]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits[0].message,'#NORUN')}}
    steps:    
        - 
            name: Checkout
            uses: actions/checkout@v4
        -
            name: Checkout code
            uses: actions/checkout@v3
        -
            name: Run Trivy vulnerability scanner in repo mode
            uses: aquasecurity/trivy-action@master
            with:
              scan-type: 'fs'
              ignore-unfixed: true
              format: 'table'
              output: 'trivy-results.txt'
              severity: 'CRITICAL'
              exit-code: 1
        - 
            name: Slack Notification
            if: failure()
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
              SLACK_ICON: https://github.com/rtCamp.png?size=48
              SLACK_MESSAGE: |
                            Failed trivy scan,see uploaded report
              SLACK_TITLE: Post Title
              SLACK_USERNAME: rtCamp
              SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        -
            name: Upload scan report
            if: failure()
            uses: MeilCli/slack-upload-file@v3
            with:
              slack_token: ${{ secrets.SLACK_TOKEN}}
              channel_id: ${{ secrets.IDNAME}}
              file_path: 'trivy-results.txt'
              initial_comment: 'Scan report by Wang Ruoqi'
        -
            name: Checkout
            uses: actions/checkout@v3
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERNAME }}
              password: ${{ secrets.DOCKERTOKEN }}
        -
            name: Build and push
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              tags: wrq123/wrq:${{github.sha}}

        -
            uses: actions/checkout@v3.5.2
            with:
              fetch-depth: 1
        - 
            name: Install Cosign
            uses: sigstore/cosign-installer@v3.1.1
           
        - 
            name: Sign image with a key
            run: |
              cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}"
            env:
              TAGS: wrq123/wrq:${{github.sha}}
              COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
              COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        - 
            name: Slack Notification
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_CHANNEL: mytest
              SLACK_MESSAGE: | 
                Name: Wang Ruoqi
                Matriculation: e1221869
                Email:e1221869@u.nus.edu
                Git: https://github.com/CarrieW1/CICD-workshop
                Image: https://hub.docker.com/repository/docker/wrq123/wrq
              SLACK_TITLE: 
              SLACK_USERNAME: DipSA 57 CICD
              SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}